name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Load environment variables from .env.test
        run: |
          if [ -f .env.test ]; then
            echo "Loading variables from .env.test"
            set -a
            source .env.test
            set +a
          else
            echo ".env.test file not found"
          fi

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest
    environment: development
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST}} << 'EOF'
            chmod +x /usr/local/repo/Todolist/devops/deploy.sh
            /usr/local/repo/Todolist/devops/deploy.sh production


            echo "Deploy script executed successfully."
          EOF
